version: '3'
services:

  mainserver:
    build: ./main
    depends_on:
      - mysqldatabase
    container_name: mainServer
    ports:
      - "81:8080"

  mysqldatabase:
    image: mysql:5.7.31
    container_name: projDataBase
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CBOdb